# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 7th International Conference on Appropriate Technology
email: icat7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  7th International Conference on Appropriate Technology ...
  Sustainable Technologies to Empower Communities – Bridging Theory with Practice
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://appropriatetech.net" # the base hostname & protocol for your site
twitter_username: approptech
github_username:  appropriatetech

# Build settings
markdown: kramdown

sass:
    load_paths:
        - _sass
        - _vendor/bootstrap
